### ISSUE TITLE
Support macOS

### ISSUE THREAD

**Issue by mgierschdev** [360CVGroup/FancyVideo#20]
Hello, any plans to support the model in macOS ? or convert the model to ml core or similar ?

thanks,

**Comment by AA-Developer** [comment]
hi
I don't have a Mac OS but I think it will work fine because it's based on Tensor.
Are you getting errors when running?

**Comment by mgierschdev** [comment]
Yes, I am getting:
Collecting xformers==0.0.23.post1 (from -r requirements.txt (line 3))
  Downloading xformers-0.0.23.post1.tar.gz (3.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 7.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/q1/2fhjcsbj38x6jvg_hkldqflw0000gn/T/pip-install-4i0pfk04/xformers_bcb3bffcd7b343b0969f7861bed49b64/setup.py", line 23, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by AA-Developer** [comment]
It's a problem because Install requirements.txt to run the model.
First you need to create an environment using conda 
Because it seems that you did not do that or that you did that and did not activate it
`git clone https://github.com/360CVGroup/FancyVideo.git
cd FancyVideo
conda create -n fancyvideo python=3.10
conda activate fancyvideo
pip install -r requirements.txt`

If this does not work for you, create an environment using Python, but make sure to use the version 3.10
Run this code in the root of the application (FancyVideo/).
c:\users\ben\appdata\local\programs\python\python310\python.exe -m venv myenv
myenv\Scripts\activate
Change the path to the path in your system.
c:\users\ben\appdata\local\programs\python\python310\python.exe 
If it doesn't work you can use the general manual installation.
When an error like this appears, it says that you need to install the mentioned package. Install it manually using the command
ModuleNotFoundError: No module named 'torch'
pip install torch

**Comment by AA-Developer** [comment]
This is due to different version compatibility.
Which environment are you using now? Anaconda or Python

**Comment by mgierschdev** [comment]
anaconda

**Comment by AA-Developer** [comment]
try this
https://github.com/AA-Developer/FancyVideo/tree/fix
If you have the original installation :
Download the file
app.py
Put it in the root
/
Download the two files
i2v_ui.yaml
t2v_ui.yaml
From the path
configs/inference
https://github.com/AA-Developer/FancyVideo/tree/fix
then run : python app.py
go to : 127.0.0.1:7860

**Comment by mgierschdev** [comment]
so it seems one of the dependencies xformers does not support macOS

**Comment by mgierschdev** [comment]
maybe I can run it in a google colab, I am interested in using the model image-to-video
