### ISSUE TITLE
[Bug] No module named 'diffusers.modeling_utils'

### ISSUE THREAD

**Issue by Milor123** [360CVGroup/FancyVideo#22]
I cant load the module guys, I've got it with git clone and pip install requirements over python 3.12, something is wrong?

```
Traceback (most recent call last):
  File "/home/noe/Documentos/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/noe/Documentos/ComfyUI/custom_nodes/FancyVideo-ComfyUI/__init__.py", line 11, in <module>
    from fancyvideo.pipelines.fancyvideo_infer_pipeline import InferPipeline
  File "/home/noe/Documentos/ComfyUI/custom_nodes/FancyVideo-ComfyUI/fancyvideo/pipelines/fancyvideo_infer_pipeline.py", line 23, in <module>
    from fancyvideo.models.cv_vae.modeling_vae import CVVAEModel
  File "/home/noe/Documentos/ComfyUI/custom_nodes/FancyVideo-ComfyUI/fancyvideo/models/cv_vae/modeling_vae.py", line 6, in <module>
    from diffusers.modeling_utils import ModelMixin
ModuleNotFoundError: No module named 'diffusers.modeling_utils'
```

**Comment by AA-Developer** [comment]
use python 3.10 or conda to creat environment 3.10
```
git clone https://github.com/360CVGroup/FancyVideo.git 
cd FancyVideo 
conda create -n fancyvideo python=3.10 conda 
activate fancyvideo pip install -r requirements.txt
```
with  environment using Python
```
git clone https://github.com/360CVGroup/FancyVideo.git 
cd FancyVideo
c:\users\ben\appdata\local\programs\python\python310\python.exe -m venv myenv
myenv\Scripts\activate
```
Use your username (Change the word : ben)

**Comment by angelyz** [comment]
Is the problem solved？

**Comment by Milor123** [comment]
> Is the problem solved？

Thank u very much guys. yes, sorry
