### ISSUE TITLE
Anyway to use FP16 version of models to reduce VRAM requirements

### ISSUE THREAD

**Issue by nitinmukesh** [360CVGroup/FancyVideo#26]
e.g. the code is using fp32 version
![image](https://github.com/user-attachments/assets/75040378-860c-405b-af3e-18d2e248d8e1)

What changes should be done to use FP16 and also anyway to reduce batch size.

I am getting OOM error after video generation.

```
Generate reference_image ...
Generate reference_image done!
Generate video ...
100%|█████████████████████████████████████████████████████████████████████████████████| 50/50 [01:52<00:00,  2.26s/it]
Traceback (most recent call last):
  File "C:\ai\FancyVideo\scripts\demo.py", line 86, in <module>
    main(args)
  File "C:\ai\FancyVideo\FV_venv\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\FancyVideo\scripts\demo.py", line 67, in main
    reference_image, video, prompt = infer_pipeline.t2v_process_one_prompt(prompt=prompt, reference_image_path=reference_image_path, seed=seed, video_length=video_length, resolution=resolution, use_noise_scheduler_snr=use_noise_scheduler_snr, fps=cond_fps, motion_score=cond_motion_score,)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\FancyVideo\fancyvideo\pipelines\fancyvideo_infer_pipeline.py", line 416, in t2v_process_one_prompt
    sample = self.text_to_video_pipeline(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\FancyVideo\FV_venv\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\FancyVideo\fancyvideo\pipelines\pipeline_animation_vae_3d.py", line 476, in __call__
    video = self.decode_latents_3d(latents)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\FancyVideo\fancyvideo\pipelines\pipeline_animation_vae_3d.py", line 276, in decode_latents_3d
    video = self.vae.decode(latents).sample
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\FancyVideo\fancyvideo\models\cv_vae\modeling_vae.py", line 299, in decode
    x = self.tiled_decode(z)
        ^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\FancyVideo\fancyvideo\models\cv_vae\modeling_vae.py", line 280, in tiled_decode
    x_i = self.spatial_tiled_decode(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\FancyVideo\fancyvideo\models\cv_vae\modeling_vae.py", line 239, in spatial_tiled_decode
    tile = self.decoder(tile)
           ^^^^^^^^^^^^^^^^^^
  File "C:\ai\FancyVideo\FV_venv\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\FancyVideo\FV_venv\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\FancyVideo\fancyvideo\models\cv_vae\vae_models.py", line 1028, in forward
    h = self.up[i_level].block[i_block](h, temb, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\FancyVideo\FV_venv\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\FancyVideo\FV_venv\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\FancyVideo\fancyvideo\models\cv_vae\vae_models.py", line 399, in forward
    h = nonlinearity(h)
        ^^^^^^^^^^^^^^^
  File "C:\ai\FancyVideo\fancyvideo\models\cv_vae\vae_models.py", line 195, in nonlinearity
    return x * torch.sigmoid(x)
           ~~^~~~~~~~~~~~~~~~~~
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.12 GiB. GPU 0 has a total capacty of 8.00 GiB of which 0 bytes is free. Of the allocated memory 9.77 GiB is allocated by PyTorch, and 4.60 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

```

**Comment by nitinmukesh** [comment]
I did tried making the change but for the first time I don't know what is wrong

![image](https://github.com/user-attachments/assets/27462ae9-c924-4b05-a3bf-bb99c08ce583)

If I remove fl32 versions it comes up with error (means it is still loading fp32)

```
 File "C:\ai\FancyVideo\fancyvideo\pipelines\fancyvideo_infer_pipeline.py", line 171, in __init__
    vae_2d = AutoencoderKL.from_pretrained(pretrained_model_path, subfolder="vae", torch_dtype=torch.float16)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\FancyVideo\FV_venv\Lib\site-packages\diffusers\modeling_utils.py", line 452, in from_pretrained
    model_file = cls._get_model_file(
                 ^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\FancyVideo\FV_venv\Lib\site-packages\diffusers\modeling_utils.py", line 593, in _get_model_file
    raise EnvironmentError(
OSError: Error no file named diffusion_pytorch_model.bin found in directory resources/models/stable-diffusion-v1-5.
```
